version: "3"

services:
  flask:
    container_name: "regulondb12_app-flask"
    build:
      context: .
      dockerfile: Dockerfile
      target: flask_app
      args:
        API_URL: /graphql
    image: regulondbunam/regulondbapp-flask:1.0.0
    depends_on:
      - datamartsApi
    networks:
      - regulondbapp

  proxy:
    container_name: "regulondb12_app-nginx"
    build:
      context: .
      dockerfile: Dockerfile
      target: proxy
    image: regulondbunam/regulondbapp-nginx:1.0.0
    ports:
      - "7001:80"
    depends_on:
      - web
      - datamartsApi
    networks:
      - regulondbapp

  web:
    container_name: "regulondb12_app-react"
    build:
      context: .
      dockerfile: Dockerfile
      target: webapp
      args:
        API_URL: /graphql
        FLASK_URL: /wdps
    image: regulondbunam/regulondbapp-react:1.4.0
    depends_on:
      - datamartsApi
      - db
      - flask
    networks:
      - regulondbapp

  datamartsApi:
    container_name: "regulondb12_app-graphql-dm"
    build:
      context: .
      dockerfile: Dockerfile
      target: graphql-dm
    image: regulondbunam/regulondbapp-graphql:1.2.0
    depends_on:
      - db
    networks:
      - regulondbapp

  db:
    container_name: "regulondb12_app-mongodb"
    build:
      context: .
      dockerfile: Dockerfile
      target: mongo
    image: regulondbunam/regulondbapp-mongo:1.3.0
    networks:
      - regulondbapp

networks:
  regulondbapp:
    driver: bridge

